2023-08-28 16:14:14.312 | INFO     | __main__:<module>:48 - Starting ArduPilot Manager.
2023-08-28 16:14:14.331 | INFO     | ArduPilotManager:__init__:52 - Loaded settings from /root/.config/ardupilot-manager/settings.json.
2023-08-28 16:14:14.332 | DEBUG    | ArduPilotManager:__init__:53 - {'preferred_board': {'manufacturer': 'Blue Robotics', 'name': 'Navigator', 'platform': 'navigator'}}
2023-08-28 16:14:14.396 | DEBUG    | asyncio.selector_events:__init__:54 - Using selector: EpollSelector
2023-08-28 16:14:14.398 | DEBUG    | flight_controller_detector.Detector:detect_linux_board:50 - Trying to detect Linux board.
2023-08-28 16:14:14.400 | DEBUG    | flight_controller_detector.Detector:detect_linux_board:52 - Navigator R5 detected.
2023-08-28 16:14:14.415 | WARNING  | ArduPilotManager:start_ardupilot:473 - More than a single board detected: [FlightController(name='Navigator', manufacturer='Blue Robotics', platform=<Platform.Navigator: 'navigator'>, path=None, flags=[]), FlightController(name='SITL', manufacturer='ArduPilot Team', platform=<Platform.SITL: 'SITL_arm_linux_gnueabihf'>, path=None, flags=[])]
2023-08-28 16:14:14.415 | DEBUG    | ArduPilotManager:get_board_to_be_used:388 - Preferred flight-controller is Navigator.
2023-08-28 16:14:14.417 | INFO     | ArduPilotManager:start_ardupilot:476 - Using Navigator flight-controller.
2023-08-28 16:14:14.455 | INFO     | ArduPilotManager:start_linux_board:234 - Using command line: '/root/.config/ardupilot-manager/firmware/ardupilot_navigator -A udp:127.0.0.1:8852 --log-directory /root/.config/ardupilot-manager/firmware/logs/ --storage-directory /root/.config/ardupilot-manager/firmware/storage/ -C /dev/ttyS0 -B /dev/ttyAMA1 -E /dev/ttyAMA2 -F /dev/ttyAMA3 --defaults /usr/blueos/userdata/firmware/ardupilot_navigatorparams.params'
2023-08-28 16:14:14.470 | DEBUG    | mavlink_proxy.AbstractRouter:start:90 - Calling router using following command: '/usr/bin/mavlink-routerd 127.0.0.1:8852 0.0.0.0:14660 --endpoint 192.168.2.1:14550 --endpoint 127.0.0.1:14000 --tcp-port 5777 -l /root/.config/ardupilot-manager/logs'.
2023-08-28 16:14:17.603 | INFO     | uvicorn.server:serve:64 - Started server process [48]
2023-08-28 16:14:17.609 | INFO     | uvicorn.lifespan.on:startup:26 - Waiting for application startup.
2023-08-28 16:14:17.617 | INFO     | uvicorn.lifespan.on:startup:38 - Application startup complete.
2023-08-28 16:14:17.624 | INFO     | uvicorn.server:_log_started_message:199 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2023-08-28 16:14:22.734 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56924 - "GET / HTTP/1.1" 200
2023-08-28 16:14:22.919 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56940 - "GET /register_service HTTP/1.1" 404
2023-08-28 16:14:22.949 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56948 - "GET /docs HTTP/1.1" 200
2023-08-28 16:14:22.975 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56950 - "GET /docs.json HTTP/1.1" 404
2023-08-28 16:14:22.997 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56952 - "GET /openapi.json HTTP/1.1" 200
2023-08-28 16:14:23.013 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56956 - "GET /v1.0/docs HTTP/1.1" 200
2023-08-28 16:14:23.274 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56958 - "GET /v1.0/openapi.json HTTP/1.1" 200
2023-08-28 16:14:23.302 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56972 - "GET /swagger.json HTTP/1.1" 404
2023-08-28 16:14:28.691 | DEBUG    | commonwealth.mavlink_comm.MavlinkComm:get_most_recent_vehicle_id:102 - 1 (detected)
2023-08-28 16:14:28.692 | INFO     | commonwealth.mavlink_comm.MavlinkComm:set_system_id:28 - system_id set to: 1
2023-08-28 16:14:28.694 | ERROR    | commonwealth.mavlink_comm.VehicleManager:get_firmware_info:69 - Failed to request autopilot version. Received empty response
2023-08-28 16:14:28.695 | INFO     | commonwealth.mavlink_comm.VehicleManager:get_firmware_info:70 - trying to get a new system id
2023-08-28 16:14:28.706 | DEBUG    | commonwealth.mavlink_comm.MavlinkComm:get_most_recent_vehicle_id:102 - 1 (detected)
2023-08-28 16:14:28.711 | INFO     | commonwealth.mavlink_comm.VehicleManager:set_target_system:26 - setting target system to: 1
2023-08-28 16:14:28.712 | ERROR    | commonwealth.utils.apis:custom_route_handler:36 - Unhandled service exception.
2023-08-28 16:14:28.714 | ERROR    | commonwealth.utils.apis:custom_route_handler:37 - Failed to get autopilot version.
Exception


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/home/pi/services/ardupilot_manager/main.py", line 252, in <module>
    loop.run_until_complete(server.serve())
    │    │                  │      └ <function Server.serve at 0xb5cc04a8>
    │    │                  └ <uvicorn.server.Server object at 0xb54a3310>
    │    └ <function BaseEventLoop.run_until_complete at 0xb63ecdf0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0xb63ecda8>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0xb63eeb68>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
    │      └ <function Handle._run at 0xb6434850>
    └ <Handle <TaskStepMethWrapper object at 0xb53fa1f0>()>
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0xb53fa1f0>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0xb53fa1f0>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0xb53fa1f0>()>
  File "/usr/local/lib/python3.9/site-packages/uvicorn-0.13.4-py3.9.egg/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
                   │   │    │      │    │        │    └ <function RequestResponseCycle.send at 0xb540a028>
                   │   │    │      │    │        └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0xb53fa1d8>
                   │   │    │      │    └ <function RequestResponseCycle.receive at 0xb540a070>
                   │   │    │      └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0xb53fa1d8>
                   │   │    └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
                   │   └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0xb53fa1d8>
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0xb543df40>
  File "/usr/local/lib/python3.9/site-packages/uvicorn-0.13.4-py3.9.egg/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0xb53fa1d8>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0xb53fa1d8>>
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
                 │    └ <uvicorn.middleware.message_logger.MessageLoggerMiddleware object at 0xb54a33a0>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0xb543df40>
  File "/usr/local/lib/python3.9/site-packages/uvicorn-0.13.4-py3.9.egg/uvicorn/middleware/message_logger.py", line 61, in __call__
    await self.app(scope, inner_receive, inner_send)
          │    │   │      │              └ <function MessageLoggerMiddleware.__call__.<locals>.inner_send at 0xb4be9100>
          │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb4be90b8>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <fastapi.applications.FastAPI object at 0xb624efd0>
          └ <uvicorn.middleware.message_logger.MessageLoggerMiddleware object at 0xb54a33a0>
  File "/usr/local/lib/python3.9/site-packages/fastapi-0.63.0-py3.9.egg/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <function MessageLoggerMiddleware.__call__.<locals>.inner_send at 0xb4be9100>
                           │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb4be90b8>
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function MessageLoggerMiddleware.__call__.<locals>.inner_send at 0xb4be9100>
          │    │                │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb4be90b8>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0xb624ed78>
          └ <fastapi.applications.FastAPI object at 0xb624efd0>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0xb4be9190>
          │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb4be90b8>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.exceptions.ExceptionMiddleware object at 0xb624ed90>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0xb624ed78>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb4be9070>
          │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb4be90b8>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <fastapi.routing.APIRouter object at 0xb624eec8>
          └ <starlette.exceptions.ExceptionMiddleware object at 0xb624ed90>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb4be9070>
          │     │      │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb4be90b8>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
          │     └ <function Mount.handle at 0xb5e42658>
          └ <starlette.routing.Mount object at 0xb549d778>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/routing.py", line 376, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb4be9070>
          │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb4be90b8>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <fastapi.applications.FastAPI object at 0xb549d988>
          └ <starlette.routing.Mount object at 0xb549d778>
  File "/usr/local/lib/python3.9/site-packages/fastapi-0.63.0-py3.9.egg/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb4be9070>
                           │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb4be90b8>
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb4be9070>
          │    │                │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb4be90b8>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0xb549d820>
          └ <fastapi.applications.FastAPI object at 0xb549d988>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0xb4be9148>
          │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb4be90b8>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.exceptions.ExceptionMiddleware object at 0xb549d658>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0xb549d820>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb4be91d8>
          │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb4be90b8>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <fastapi.routing.APIRouter object at 0xb549d928>
          └ <starlette.exceptions.ExceptionMiddleware object at 0xb549d658>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb4be91d8>
          │     │      │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb4be90b8>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
          │     └ <function Route.handle at 0xb5e42070>
          └ <commonwealth.utils.apis.GenericErrorHandlingRoute object at 0xb559d9d0>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb4be91d8>
          │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb4be90b8>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <function request_response.<locals>.app at 0xb61dd4f0>
          └ <commonwealth.utils.apis.GenericErrorHandlingRoute object at 0xb559d9d0>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/routing.py", line 41, in app
    response = await func(request)
                     │    └ <starlette.requests.Request object at 0xb53fac10>
                     └ <function GenericErrorHandlingRoute.get_route_handler.<locals>.custom_route_handler at 0xb61dd610>
> File "/usr/local/lib/python3.9/site-packages/commonwealth-0.1.0-py3.9.egg/commonwealth/utils/apis.py", line 31, in custom_route_handler
    return await original_route_handler(request)
                 │                      └ <starlette.requests.Request object at 0xb53fac10>
                 └ <function get_request_handler.<locals>.app at 0xb61dd580>
  File "/usr/local/lib/python3.9/site-packages/fastapi-0.63.0-py3.9.egg/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0xb5e2a190>
  File "/usr/local/lib/python3.9/site-packages/fastapi-0.63.0-py3.9.egg/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {}
                 │         └ <function get_firmware_info at 0xb61dd778>
                 └ <fastapi.dependencies.models.Dependant object at 0xb559d478>

  File "/home/pi/services/ardupilot_manager/main.py", line 115, in get_firmware_info
    return await autopilot.vehicle_manager.get_firmware_info()
                 │         │               └ <function VehicleManager.get_firmware_info at 0xb575ce80>
                 │         └ <commonwealth.mavlink_comm.VehicleManager.VehicleManager object at 0xb624ec70>
                 └ <ArduPilotManager.ArduPilotManager object at 0xb624ecb8>

  File "/usr/local/lib/python3.9/site-packages/commonwealth-0.1.0-py3.9.egg/commonwealth/mavlink_comm/VehicleManager.py", line 72, in get_firmware_info
    raise ValueError("Failed to get autopilot version.") from Exception

ValueError: Failed to get autopilot version.
2023-08-28 16:14:28.800 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:57350 - "GET /v1.0/firmware_info HTTP/1.0" 500
2023-08-28 16:14:29.523 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:57280 - "GET /v1.0/vehicle_type HTTP/1.0" 200
2023-08-28 16:14:31.596 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:57392 - "GET /v1.0/vehicle_type HTTP/1.0" 200
